baseURL = "https://lsxnr.com/"
languageCode = "en-gb"
title = "lsxnr"
theme = "base16"

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
    [[params.customCSS]]
        href = "css/images.css"

