baseURL = "https://lsxnr.com/"
languageCode = "en-gb"
title = "lsxnr"
theme = "base16"
enableRobotsTXT = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[imaging]
resampleFilter = "catmullrom"

[params]
  author = "Denis Igorevich Lobanov"

  Paginate = 10
  [[params.customCSS]]
    href = "css/images.css"

